// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.src.Infrastructure.Migrations
{
    [DbContext(typeof(RadarDbContext))]
    [Migration("20250916204733_AddOrganizadorIdToEvento")]
    partial class AddOrganizadorIdToEvento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Eventos.Chaveamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("TravadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("chaveamentos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Eventos.Confronto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChaveamentoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("EhBye")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("IdStatusConfronto")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParticipanteAId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParticipanteBId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RodadaChaveamentoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("VencedorId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("VencedorPorWalkover")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("RodadaChaveamentoId");

                    b.ToTable("confrontos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Eventos.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EhRecorrente")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int?>("MaximoParticipantes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeLocal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrganizadorId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("QuantidadeVagasFixas")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeVagasSorteio")
                        .HasColumnType("int");

                    b.Property<Guid?>("SerieEventoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Eventos.InscricaoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("InscritoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UsuarioMcId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("inscricoes_evento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Eventos.McFixoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioMcId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("mcs_fixos_evento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Eventos.McPreSelecionadoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioMcId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("mcs_pre_selecionados_evento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Eventos.RodadaChaveamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChaveamentoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("NumeroRodada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChaveamentoId");

                    b.ToTable("rodadas_chaveamento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Eventos.VitoriaMcEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataVitoria")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioMcId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("vitorias_mc_evento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Noticia.Noticia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("noticias", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Timeline.RegistroTimeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("EventoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Metadados")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("registros_timeline", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Usuarios.Papel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("papeis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Nome = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Nome = "ORGANIZADOR"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Nome = "MC"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Nome = "VISUALIZADOR"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuarios.PapelPermissao", b =>
                {
                    b.Property<Guid>("PapelId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("char(36)");

                    b.HasKey("PapelId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("papeis_permissoes", (string)null);

                    b.HasData(
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003e8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003e9-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003ea-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003eb-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003ec-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003ed-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003ee-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003ef-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003f0-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003f1-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003f2-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003f3-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003f4-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003f5-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003f6-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003f7-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003f8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003f9-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003fa-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003fb-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissaoId = new Guid("000003fc-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003e8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003e9-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003ea-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003eb-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003ec-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003ed-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003ee-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003f0-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003f4-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003f5-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003f6-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003f7-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003f8-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissaoId = new Guid("000003f9-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PermissaoId = new Guid("000003f2-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PermissaoId = new Guid("000003f3-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PermissaoId = new Guid("000003fa-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PermissaoId = new Guid("000003fb-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            PapelId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PermissaoId = new Guid("000003fc-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuarios.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("permissoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("000003e8-0000-0000-0000-000000000000"),
                            Codigo = "eventos.criar"
                        },
                        new
                        {
                            Id = new Guid("000003e9-0000-0000-0000-000000000000"),
                            Codigo = "eventos.abrirInscricoes"
                        },
                        new
                        {
                            Id = new Guid("000003ea-0000-0000-0000-000000000000"),
                            Codigo = "eventos.fecharInscricoes"
                        },
                        new
                        {
                            Id = new Guid("000003eb-0000-0000-0000-000000000000"),
                            Codigo = "eventos.sortearChaveamento"
                        },
                        new
                        {
                            Id = new Guid("000003ec-0000-0000-0000-000000000000"),
                            Codigo = "eventos.ressortearChaveamento"
                        },
                        new
                        {
                            Id = new Guid("000003ed-0000-0000-0000-000000000000"),
                            Codigo = "eventos.registrarVencedor"
                        },
                        new
                        {
                            Id = new Guid("000003ee-0000-0000-0000-000000000000"),
                            Codigo = "eventos.finalizar"
                        },
                        new
                        {
                            Id = new Guid("000003ef-0000-0000-0000-000000000000"),
                            Codigo = "noticias.publicar"
                        },
                        new
                        {
                            Id = new Guid("000003f0-0000-0000-0000-000000000000"),
                            Codigo = "noticias.lerRascunhos"
                        },
                        new
                        {
                            Id = new Guid("000003f1-0000-0000-0000-000000000000"),
                            Codigo = "doacoes.registrar"
                        },
                        new
                        {
                            Id = new Guid("000003f2-0000-0000-0000-000000000000"),
                            Codigo = "eventos.inscricao.criar"
                        },
                        new
                        {
                            Id = new Guid("000003f3-0000-0000-0000-000000000000"),
                            Codigo = "eventos.ler.abertos"
                        },
                        new
                        {
                            Id = new Guid("000003f4-0000-0000-0000-000000000000"),
                            Codigo = "eventos.inscricoes.listar"
                        },
                        new
                        {
                            Id = new Guid("000003f5-0000-0000-0000-000000000000"),
                            Codigo = "eventos.fixos.definirVagas"
                        },
                        new
                        {
                            Id = new Guid("000003f6-0000-0000-0000-000000000000"),
                            Codigo = "eventos.fixos.definirLista"
                        },
                        new
                        {
                            Id = new Guid("000003f7-0000-0000-0000-000000000000"),
                            Codigo = "eventos.preselecao.criar"
                        },
                        new
                        {
                            Id = new Guid("000003f8-0000-0000-0000-000000000000"),
                            Codigo = "eventos.mc.removerPorWo"
                        },
                        new
                        {
                            Id = new Guid("000003f9-0000-0000-0000-000000000000"),
                            Codigo = "confrontos.wo.registrar"
                        },
                        new
                        {
                            Id = new Guid("000003fa-0000-0000-0000-000000000000"),
                            Codigo = "mc.wo.lerProprio"
                        },
                        new
                        {
                            Id = new Guid("000003fb-0000-0000-0000-000000000000"),
                            Codigo = "ranking.ler"
                        },
                        new
                        {
                            Id = new Guid("000003fc-0000-0000-0000-000000000000"),
                            Codigo = "eventos.ler.publico"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("EhMc")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EhOrganizador")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Usuarios.UsuarioPapel", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PapelId")
                        .HasColumnType("char(36)");

                    b.HasKey("UsuarioId", "PapelId");

                    b.HasIndex("PapelId");

                    b.ToTable("usuarios_papeis", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Eventos.Confronto", b =>
                {
                    b.HasOne("Domain.Entities.Eventos.RodadaChaveamento", null)
                        .WithMany("Confrontos")
                        .HasForeignKey("RodadaChaveamentoId");
                });

            modelBuilder.Entity("Domain.Entities.Eventos.RodadaChaveamento", b =>
                {
                    b.HasOne("Domain.Entities.Eventos.Chaveamento", null)
                        .WithMany("Rodadas")
                        .HasForeignKey("ChaveamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Usuarios.PapelPermissao", b =>
                {
                    b.HasOne("Domain.Entities.Usuarios.Papel", "Papel")
                        .WithMany("PapelPermissoes")
                        .HasForeignKey("PapelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuarios.Permissao", "Permissao")
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Papel");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("Domain.Entities.Usuarios.UsuarioPapel", b =>
                {
                    b.HasOne("Domain.Entities.Usuarios.Papel", "Papel")
                        .WithMany()
                        .HasForeignKey("PapelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany("UsuarioPapeis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Papel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Eventos.Chaveamento", b =>
                {
                    b.Navigation("Rodadas");
                });

            modelBuilder.Entity("Domain.Entities.Eventos.RodadaChaveamento", b =>
                {
                    b.Navigation("Confrontos");
                });

            modelBuilder.Entity("Domain.Entities.Usuarios.Papel", b =>
                {
                    b.Navigation("PapelPermissoes");
                });

            modelBuilder.Entity("Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Navigation("UsuarioPapeis");
                });
#pragma warning restore 612, 618
        }
    }
}
